name: smartCart
description: "This app assists users in managing their grocery lists efficiently. It aims to streamline the process of creating, organizing, and accessing grocery lists, making shopping trips more organized and convenient."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.4
  font_awesome_flutter: ^10.7.0
  google_sign_in: ^6.2.1
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  provider: ^6.1.1
  rive: ^0.12.4
  sqflite: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/RiveAssets/
