// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNf5Ri1rmd2vd9lr7nWHJ_DNn-a1NRqGA',
    appId: '1:716741597267:web:f5961cc314f6a02b0c4ea6',
    messagingSenderId: '716741597267',
    projectId: 'smartCart-b88cf',
    authDomain: 'smartCart-b88cf.firebaseapp.com',
    storageBucket: 'smartCart-b88cf.appspot.com',
    measurementId: 'G-QMYT2FLW6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLx0MRaowG_f1Sf4ecE9f5r2Dxh_vRsDQ',
    appId: '1:716741597267:android:22cbf84132ed25180c4ea6',
    messagingSenderId: '716741597267',
    projectId: 'smartCart-b88cf',
    storageBucket: 'smartCart-b88cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvgCt47UGXzdj05bIDgvo02QOkya8eD5E',
    appId: '1:716741597267:ios:68628abe4b33a3e40c4ea6',
    messagingSenderId: '716741597267',
    projectId: 'smartCart-b88cf',
    storageBucket: 'smartCart-b88cf.appspot.com',
    iosClientId:
        '716741597267-su7ok5mik29f85snaumfc5hrmnn3lr98.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartCart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvgCt47UGXzdj05bIDgvo02QOkya8eD5E',
    appId: '1:716741597267:ios:ac13e3154d05a7b50c4ea6',
    messagingSenderId: '716741597267',
    projectId: 'smartCart-b88cf',
    storageBucket: 'smartCart-b88cf.appspot.com',
    iosClientId:
        '716741597267-1snlv6jh3k4918ajkf5kdls8020qtcq6.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartCart.RunnerTests',
  );
}
